Bug fixed

diff --git a/11-functions-sh b/11-functions-sh
--- a/11-functions-sh
+++ b/11-functions-sh
@@ -4,28 +4,28 @@ ID=$(id -u)
 
 if [ $ID -ne 0 ]
   then
-      echo "Error: Please Log with root useR access"
+      echo "Error: Please as a  root user "
       exit 1
 else
-      echo "Logging as root user"
+      echo "You are root user"
 fi
+
+VALIDATE(){
+
+  if [ $? -ne 0 ]
+    then 
+      echo "Installation  failed!!"
+      exit 1
+  else
+      echo "Installtion succesfull!"
+   fi
+}
+
+
 
 yum install mysql -y
+VALIDATE 
 
-if [ $? -ne 0 ]
-  then 
-      echo "Mysql installation got failed!!"
-      exit 1
-else
-    echo "Mysql installtion succesfull!1"
-fi
 
 yum install git -y
-
-if [ $? -ne 0 ]
-  then
-      echo "Error: The git is not installed" 
-      exit 1
-else
-      echo "Git is installed succesfully!!"
-fi
+VALIDATE
